language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

install:
  - pip install .
  - pip install "pytest>=3.4" codecov

after_success:
  - codecov

script:
  - coverage run --source=wakati -m pytest -v
